### PR TITLE
solaris: layers, categories, banks, types

### PR DESCRIPTION
**Pull request by conversy**
use Python's generators for SysEx browsing back and forth.
use Python 3.10's structural matching for SysEx recognition.

### CODE REVIEW

**Comment by christofmuc** [comment]
@conversy Cool stuff, I hadn't seen that Python 3.10 feature before. Looks very useful! I do have the question though - not every user of KnobKraft is on Python 3.10, many are still on 3.8, especially those with Windows 7 computers. I know, old stuff, but it seems we need to build in at least a version check? KK loads all modules on startup, and if it cannot parse the Python code, that module will throw errors and not load, hopefully not taking down the whole Librarian with it :-/

**Comment by conversy** [comment]
Sorry I thought that Python 3.10 was mandatory for KnobKraft!
Yes, pattern matching seems particularly suitable for this kind of parsing. 
Ok I'll see what needs to be done, at least a version number check.

**Comment by conversy** [comment]
It seems that it is not possible to write code with `match xxx:` that would not raise a `SyntaxError` in Python < 3.10. So I think verifying the version will not be possible without experiencing an exception.
However, we can use a 2-step `import scheme`: `JB_Solaris.py`  could contain:
```
import sys
if sys.version_info >= (3,10):
    from JB_Solaris_310 import *
else:
    print("Error: Solaris adaptation requires Python 3.10 or later")
```

and the current `JB_Solaris.py` could be renamed to `JB_Solaris_310.py`. This way, no import exception would be raised. This also requires that `JB_Solaris_310` be in another directory than `adaptations` so as to avoid importing it...

What do you think?
Or, I revert back to my previous code, which is a shame, since structural matching leads to so much nicer code...

**Comment by conversy** [comment]
I reverted back to 3.8-compatible code. You may merge if it please you.

**Pull request merged**
