### PR TITLE
Create JB_Solaris.py

### PR DESCRIPTION
**Pull request by conversy**
This a (still incomplete) adaptation for the John Bowen Solaris synthesizer. The adaptation is able to discover a Solaris unit, receive an Edit Buffer and find the name of the preset, but it's not able to send a preset so far, I do not know if the Solaris sysex implementation is able to accept it.

### CODE REVIEW

**Comment by christofmuc** [comment]
@conversy Pretty cool! I will have a look at the code and see if I can spot any improvements possible! Also, if you have a single patch sysex file to upload, we can put it into the test data directory and hook the adaptation into the test suite.

**Comment by conversy** [comment]
Thank you. For the test data, I'll do it later, I'm not able to do it for a few weeks.

**Comment by conversy** [comment]
Hi, I uploaded a sysex file, and added some tests, though they should be completed later. Is there anything preventing this PR to be merged that I can do? Best, Stéphane.

**Comment by christofmuc** [comment]
Hi Stéphane, thank you! No, everything is fine, I am just preparing the 2.0.0 beta release which sucks up my time. Will hopefully do the release today! I'll merge this in for the release!

**Pull request merged**
